### ISSUE TITLE
resources2 Cross Platform Issue

### ISSUE THREAD

**Issue by mstreatfield** [nerdvegas/rez#167]
I've been taking a look at porting the changes I made in #159 to the resources2 branch.  

The main issue I've discovered (which is quite pervasive) relates to the `get_repository` method of the `PackageRepositoryManager` class.  As this splits on `:`, it trips up on any Windows path.  For example, it thinks the repository type of `c:\users\markst\packages` is `c`.

Based on the code docstrings I've workaround this by qualifying the rez configuration so that the path becomes `filesystem:c:\users\markst\packages`.  And for the most part this works well - although I've had to sprinkle it quite liberally through the test cases that defined their own packages path.

The main stumbling block is the build process code.  Here we are passing paths around which are detached from any repository plugin (and, depending on the configuration any repository identifier such as `filesystem:`).  Some methods (for example `_build_variant_base` on `LocalBuildProcess` and `pre_release` on `BuildProcessHelper`) need both representations.

Either I have to assume they are `filesystem:` based and so hardcode this prefix onto internal calls to `iter_packages` etc but so far this is resulting in a lot of changes.  This results in lots of code like:

    release_path = "filesystem:" + self.package.config.release_packages_path 

Or, configure rez such that `filesystem:` is always included (in `rezconfig`) and then use the following to get the actual file path in these methods:

    release_path = self.package.config.release_packages_path # "filesystem:..."
    repo = package_repository_manager.get_repository(release_path)
    if not os.path.exists(repo.location):
        raise ReleaseError("Release path does not exist: %r" % release_path)

The former feels wrong so I am leaning towards the latter.  Is that the right thing to do?  It means doing it in a couple of places though which feels a bit untidy however. 

I think it's easy to replicate this on linux too - if you update your configuration to include `filesystem:` in `rezconfig` and then try and build/release you should hit the same issues (although I haven't actually tried that).

**Comment by nerdvegas** [comment]
Hey Mark,

1) Shouldn't packages_path be splitting on os.pathsep, thus ';' on Windows? Is that not the case?

2) I hadn't put a lot of thought into this because I'd considered that adding a new package repo type would be a fair way off - but the Windows port has unexpectedly bought this to the fore. My vote is to simply avoid the problem completely by choosing a different repo/path delimiter - I think '@' is the best candidate.

Thus:
filesystem@/srv/packages

What do you think?
A

**Comment by mstreatfield** [comment]
1. Yes.  `C:\path\a;C:\path\b` is correctly split to `['C:\path\a', 'C:\path\b']`.  It's when the repository manager than tokenises `'C:\path\a'` to work out the repository type that things break.

2. Yes.  I did consider that.  And it is definitely the easiest solution.  I'll go with `@` and update my changes/code appropriately.  

I was thinking about this wrt a database repository - presumably this would be something like `database:mongodb://username:password@host:port`.  This is fine for the metadata repository, but not the code that is installed.  At the moment we lump the two together and assume the metadata repository is the same as the code (install?) repository.  For a database backend though we have to separate those concerns a little.

**Comment by nerdvegas** [comment]
Yeah I'd realised that also. You may have noticed in resources2 that 'base' has become a package attribute - that's why. I anticipated that a database backend would need to explicitly specify 'base', since it can't be implied in that case.

Probably enough hasn't been done yet for this to actually work when adding a database backend. I figured that would become evident when I actually try to do that. Which might actually be happening soon... more news on that later.

**Comment by nerdvegas** [comment]
We should start thinking about what the various repository uris might look like. It's actually going to be a pain when storing these in REZ_PACKAGES_PATH, since we want to avoid pathsep (and yet host:port is a common pattern as shown in your last comment).

When specifying release path, we're going to have to list both repo uri, and physical path, since as you mentioned a database uri doesn't tell rez where to actually install the package payload to.

So for eg, here's an example mongo uri for releasing, which avoids pathsep, and specifies install path (not that I like it):

mongodb@uname=uname,pwd=pwd,host=host,port=port,path=/svr/packages

Actually, it's not so bad?
A

**Comment by nerdvegas** [comment]
Further to this. I think the release path doesn't have to be part of the package repo uri - to do a release, we need an install path (currently REZ_RELEASE_PATH) and optionally a pkg repo URI (currently implied as 'filesystem' repo that matches release path). So all we need is another setting - REZ_RELEASE_PACKAGE_REPOSITORY. If set, the package metadata goes there (but does it also go to the filesystem repo?).

REZ_PACKAGES_PATH stays as-is - a list of package repos, where a filepath indicates a 'filesystem' type repo matching that path.

**Comment by nerdvegas** [comment]
Closing as we've switched to '@' delimiter.
