### ISSUE TITLE
Why are there pre build_commands and no post build_commands

### ISSUE THREAD

**Issue by SKY123C** [nerdvegas/rez#1878]
# The Issus
Why are there pre build_commands and no post build_commands

**Comment by beatreichenbach** [comment]
Any command that would run after the build is finished can just be run as part of your `build_command`.

For example if you have a `build.sh` and as part of your "post_build" you want to clean up temp files, you could just append this to your build script:
```sh
rm -rf "$REZ_BUILD_PATH"
```

So there isn't really any need for post build commands.

**Comment by JeanChristopheMorinPerso** [comment]
To clarify @beatreichenbach answer, the pre-build commands function exists so that you can set environment variables before the builds happen. See https://rez.readthedocs.io/en/stable/package_commands.html#pre-build-commands. I don't think it would make sense to have a post-build command here.

The various commands functions exists to allow the package author to modify the environment created by rez.
