### ISSUE TITLE
Filesystem Repository Too Strict

### ISSUE THREAD

**Issue by mstreatfield** [nerdvegas/rez#193]
Currently, if an environment is resolved while a package is mid-release you can an error like:

    rezplugins.package_repository.filesystem.PackageDefinitionFileMissing: Missing package definition file: FileSystemPackageResource({'version': '1.0.0', 'repository_type': 'filesystem', 'location': '/packages', 'name': 'Foo'})

The problem, I believe is that the package.yaml is created at the end of the release process, but the package family and version folder are (obviously) created early.  As a result the filesystem resource starts to see them and complain about the missing package.yaml.

On the whole this isn't a problem, but we have a number of packages which take a long time to release (5+ minutes) so we are starting to hit this.  Could we make things a little more tolerant so it only issues a warning if the package definition file is missing?  This could also be configurable - either whether to warn or not, or whether to raise an exception or not.

Has anyone else discovered this?

**Comment by elrond79** [comment]
I encountered something similar on testing, but haven't in production yet.
In general, though, I think it might be a good idea to have a way to have a
folder in the packages path that isn't a rez family package; either:

- not consider a folder a package family folder unless it can find a
package.* file somewhere within, or
- have a way to mark a folder (with some sort of sentinal file perhaps,
".not_rez"?) as not being a family package folder
- have a .rezignore file (or setting) or set folders to be ignored

In the first case, the folder wouldn't be picked up until the release is
finished (and the .yaml / .py is made); and the second/third, we could
create the ".not_rez" (or rezignore) at the start, and then delete it when
we finish.

**Comment by nerdvegas** [comment]
I'll look into this but I think what's happening is that Rez looks only at the version folder initially - the package.yaml is only loaded when other package attributes are touched. This is an important optimisation (you always want to load pkg data as lazily as possible). So in the current setup, it wouldn't be possible to simply issue a warning - you have a Package instance, yet its contents are there - an error has to be raised.

There are two things we could do. 
(1) Check for a package.yaml/py within the version dir before assuming it's a package. Con - slightly higher cost since more file stats will occur.
(2) Change the release process so that if the version dir doesn't already exist, it installs to a tmp dir in the same place, then does a mv at the end of the install. Cons - could lead to complicated scenarios where two build hosts are trying to install different variants into the same package at the same time, and one ends up mv'ing after the other, overwriting the changes. Actually thinking more about this I think it's a non-starter.

@elrond79 - checking for a package.yaml/py at the package family level is not an option IMO, the extra cost in searching for a file in this case is too high. And it's not so bad to occasionally see a package family that doesn't contain any packages.

The .rezignore approach would work but it feels maybe more complicated than we need. Certainly more things could go wrong if we try automatically adding pkgs to this file, we'd have to consider file locking etc.

The simplest approach seems to be (1). I'll look into it. Maybe I can still avoid a lot of the extra stats by only performing this extra check on directories that have a ctime within X seconds of now (which would be configurable).

**Comment by nerdvegas** [comment]
This was a simple change that seems to work. It's available in branch 'fix_missing_pkg_file'. As mentioned, the new behaviour is to just ignore versioned directories that don't contain a package.* file - imo this is more correct anyway, it's reasonable to say that if package.* isn't there, then it isn't a package.

Mark, can you give this a test and let me know it works, and I'll merge back into resources2.

Wrt resources2, I'm thinking it's high time we merge back to master, I'm worried too many people are getting confused about where to look - there was a recent mail from someone who may have been using the 2.0 branch. So I'm thinking about branching master to 'rez-1-legacy', then merging resources2 onto master.

**Comment by elrond79** [comment]
I'm all in favor of merging resources2 back into master. It's clear this is where things are headed.

I'd also like to get rid of the stuff in "to_delete" - keeps on cluttering my search results... and while we're at it, might be a good time to rename the various names ending with underscores back (ie, packages_.py)

**Comment by nerdvegas** [comment]
Yep. I'll do the file renaming and deletions in one commit, followed by a merge to master. Will happen either today or Monday.

A

**Comment by elrond79** [comment]
Ah - I may have jumped the gun by creating a pull request for a branch that removes to_delete, then. Feel free to ignore it if you'd prefer to just do it all in one go...

**Comment by nerdvegas** [comment]
Anyone had a chance to test this? I'm pretty confident the fix works, just want to get other eyes on it before I merge to resources2.

**Comment by mstreatfield** [comment]
I'll try and look today.  I got pulled on to a few other things and so not had a chance to look at this or the alias/string quoting issue.

> So I'm thinking about branching master to 'rez-1-legacy', then merging resources2 onto master.

It is also possible to set the default branch in GitHub (under the settings for the repository).  So, if for some reason the merge is delayed, you can set the default branch to resources2.

**Comment by mstreatfield** [comment]
With this change, I no longer get the error I was originally seeing.  So for that contrived test case this branch appears to be ok.

> So I'm thinking about branching master to 'rez-1-legacy', then merging resources2 onto master.

Can I also suggest you tag the repository with the version of rez whenever you update the `version.py` file?  i.e before you add the commit with the new number, tag with the old one.  It helps us integrate your changes if I can more easily find where I am in the history.

**Comment by nerdvegas** [comment]
@mstreatfield,

Ok I'll start tagging as soon as I merge back to master and do the file renaming, should be soon (after I get through the recent spate of PRs).

Thinking about following a gitflow-like branching schema - ie, merge back to master, then start a 'develop' branch off master that becomes the primary development branch. Then hopefully within the next few months, start a release candidate branch off develop, then at long last, merge this back to master and tag as the elusive 2.0.0.
A

**Comment by nerdvegas** [comment]
Merged fix, closing.
