### ISSUE TITLE
(K)Ubuntu 15.10 support

### ISSUE THREAD

**Issue by boberfly** [nerdvegas/rez#254]
Hi,

On a fresh install of (K)Ubuntu 15.10 I've installed rez from the git source by doing the following in the git directory:
python ./install.py -v $HOME/Programs/rez
And then edited my .bashrc by adding:
export PATH=$PATH:"$HOME/Programs/rez/bin/rez"
source "$HOME/Programs/rez/completion/complete.sh"
Restarted my bash session to load in the .bashrc and then did:
mkdir $HOME/packages
rez-bind rez
All of this works well, but when I do a:
rez-env rez
It says package not found, and it does search into my home directory, and I also create a dummy package which has a basic package.py, and it does the same thing. The $HOME/pacakges/rez directory does exist.

Is there something I'm missing? Does (K)Ubuntu 15.10 do some strange things?

Cheers!

**Comment by nerdvegas** [comment]
Hi Alex,

What specific 'package not found' error do you get? You're probably missing
the rez packages that rez itself depends on - platform, arch, os and python.

If you make a copy of the 'repository' directory you will see that these
packages are listed there, and you can add/update them for your own
purposes. For example, there is a platform-Ubuntu-12.04 package, you should
make a copy of these and repurpose for Ubuntu-15.10. You can "rez-build -i"
each one, and it will be installed into ~/packages. You need to do this in
reverse dependency order - ie start with 'platform' and work up - otherwise
an attempt to build a package will result in 'package not found' error for
one of its dependencies.

The 'python' package requires the 'gcc' package, but if you don't want to
try and build this yet (it's a big build, things can go wrong) then you can
just comment out python's gcc requirement before you rez-build it, and it
should use the system C++ compiler.

Once you have these prerequisite packages built and installed to
~/packages, the rez package should work.

Just as way of explanation: Rez itself is already installed and you can use
all the tools such as rez-env. "rez-bind rez" creates a *rez package of rez
itself*. You only need to do this if you want to use its API. The rez
install and the commandline tools that it provides are standalone and sit
outside of rez packages.

Let me know if you have any problems,
A
