### ISSUE TITLE
question about multi variants/versions

### ISSUE THREAD

**Issue by mikeshuangyan** [nerdvegas/rez#350]
Hello,

I have a question about variants,I don't know how to set the variants in packages.py when the plugin have more than 1 version/variant.
For example,I have a plugin have  version 1.0 and 2.0 and also this plugin works for maya2015 and maya2016,and I also need the platform as variants.

current disk structure:
/rez/packages/foo
|-- 1.0
|   |-- platform-windows
|   |   |-- arch-AMD64
|   |   |   |-- os-windows-6.1.7601.SP1
|   |   |   |   |-- maya2015
|   |   |   |   |-- maya2016
|-- 2.0
|   |-- platform-windows
|   |   |-- arch-AMD64
|   |   |   |-- os-windows-6.1.7601.SP1
|   |   |   |   |-- maya2015
|   |   |   |   |-- maya2016

I don't know how to set the packages.py or what is the best way to setup the disk structure.

Thanks,
Lu

**Comment by michaelmovies** [comment]
I'm just another user, but I can speak to what we've done.

Our disk structure is basically the same, though personally I'd change the maya version strings:

```
$REZ_PACKAGE_PATH/
    [package name]/
        [package version]/
            platform-[platform type]/
                arch-[cpu architecture]/
                    os-[os release version]/
                       maya-[maya version number]
```

And the package.py file would include this:

```
name = [package name]
version = [package version]
variants = [
    [
        'platform-[platform type]',
        'arch-[cpu architecture]',
        'os-[os release version]',
        'maya-[maya version number]',
    ],
    [
        [other variants ...]
    ],
]
```

Basically you're saying that "this version of my package runs inside the cumulative environment created by this variant, and does not run in any other."

**Comment by mikeshuangyan** [comment]
@michaelmovies 
Thanks for you reply.
Yes,our disk structure and package.py are the same,but on windows when I type
"rez-env package-version",I will get the error:"rez: PackageFamilyNotFoundError: package family not found: maya".If I remove the maya version in my disk structure,it works fine.

**Comment by michaelmovies** [comment]
Ahh. My only guess for how that happens is if you do you not have Maya itself installed as a package.  Is that the case?

If it is, each part of a "variant" is, by definition, a package.  The Platform, Arch, and OS packages are given to you "for free" because Rez knows how to suss them out from the environment (that's why you can "rez bind" them), but unless you install Maya as its own package and with its own versions then Rez cannot know about the "maya" package family, hence it cannot resolve a solution for you.

I was assuming you'd already installed maya as a Package and your disk structure was specific to a new package with variants.  Your disk structure should then look like so:

```
/rez/packages/maya/
    2015/
       package.py
       [...]
    2016/
        package.py
        [...]
/rez/packages/foo
    1.0/
        package.py
        platform-windows/
            arch-AMD64/
              os-windows-6.1.7601.SP1/
                  maya-2015/
                     [...]
[... and so on ...]
```

Does that help?

**Comment by michaelmovies** [comment]
The maya package.py, by the way, would only need variants for platform, arch, and os ... because any given Maya .exe file will have been compiled against those three things. In other words giving Rez the ability to know which "variant" of Maya to use (and therefore where to install the actual .exe files) means letting Rez "know" about the context of platform + arch + os ... but any given plugin of Maya is also dependent / related / compiled to a specific version of Maya that is also within that os ... which is why we add the extra maya-version level to the variant encapsulation.  The point is that the "variants" describe a file structure of where executable files that will work in the context of that variant are to be found.

**Comment by mikeshuangyan** [comment]
@michaelmovies 
Thank you very much,It's really helpful。
Now I have create a "maya" package with platform\arch\os and only put the shortcut inside it,everything works fine now.

**Comment by nerdvegas** [comment]
Closing; please direct any future questions to the google group, thx: https://groups.google.com/forum/#!forum/rez-config
