### ISSUE TITLE
Question about migrating to rez

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#352]
Hi. Our department at Imageworks is thinking about moving to rez for managing versions and environments. Unfortunately, our existing setup is too messy to allow for a clean way to port over. 

- Is there a way to use `rez-env` in such a way that it acts on the existing environment instead of setting up an entirely new one? Something like like `virtualenv`'s `--system-site-packages` option where we have access to all existing env vars would work as well.  Our thinking is to set up packages to only append dirs under `{root}` where appropriate, and then add lower level dependencies (like python) later as we go.
- Failing that, is there a way to resolve packages and bake out their env into a .sh or .csh file that can be sourced? If we could execute each package's `commands()` and save that out, that would probably do the trick.

I hope that makes sense, and apologies if these are stupid questions - I'm just getting started with rez but don't want to go too deep into the rabbit hole quite yet. If you have other suggestions on good ways to migrate I would love to hear them.

Thanks!

**Comment by instinct-vfx** [comment]
As for the first one that should already be true unless i misunderstood the question. rez does not remove env variables or paths from PATH or the likes.

As for the second point, yes you can output the commands in different ways. When you use rez-env there is a context file created as well as shell scripts (or batch files) to create this context. The exact path is available in the environment variable REZ_CONTEXT_FILE in the resolved shell.

Cheers,
Thorsten

**Comment by larsbijl** [comment]
you can get the context as a bash script like this.

`rez-env <some packages> -c 'rez context -i'`

i'm sure there's a better way

**Comment by ttanimura** [comment]
Awesome. Thank you Thorsten and Lars! `REZ_CONTEXT_FILE` and `rez-context -i` is exactly what i was looking for :+1:

**Comment by nerdvegas** [comment]
Yo Taisuke!

So yes, rez-env + rez-context -i is your friend.

The issue that you're going to hit up against, and that you may need to
massage around atm, is that rez will _overwrite_ any path-like env-vars
that it appends/prepends, on first write. In other words, if you have a
package that appends PYTHONPATH, then if it's the first to take effect,
it'll actually do an export and overwrite that value. The reason is, if
this did not happen, then a rez-env'd environment would simply append to
existing values, leaving whatever pre-rez-env cruft on PYTHONPATH intact.
Meaning of course that your env wouldn't really be correctly configured,
since a python import could easily bring in something that rez did not
configure.

IMO you don't have enough control over this process right now. I would like
to give users more fine-grained control, so that different modes of
operation can be set, both global and per-variable. For example, often the
most useful behavior would be to append to PYTHONPATH at the end of rez'
actions, the pre-rez value. So if PYTHONPATH were X before rez-env, and
rez-env set it to Y:Z, then the end result should be Y:Z:X.

There is a setting you can use currently, though it is a blunt instrument:
https://github.com/nerdvegas/rez/wiki/Configuring-Rez#all_parent_variables

Hth,
A

**Comment by ttanimura** [comment]
Hey Allan! I discovered `all_parent_variables` last week and it is the silver bullet that will allow us to transition without having to rejig large chunks of our pipeline :)

I agree that this hybrid approach of keeping existing variables rather than overwriting them makes the barrier to entry much lower. It makes it easier to wedge Rez into established pipelines and play around with it. So far its looking great!
