### ISSUE TITLE
Question regarding build time env vars

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#358]
We have a package that contains things like common cmake files, Doxygen configs etc that other packages use at build time. We want to add extra behaviour to these build files that are controlled with environment variables. Ideally these env vars would be set in the package being built, but I'm not sure how to do this, as only the dependencies' packages seem to be evaluated at build time. 

Is there something we can put into a package's `package.py` that gets evaluated at build time? Essentially the equivalent of the snippet below, that is executed when `rez-build` is run:
```
def commands():
    if building:
        env.SOME_BUILD_ENV_VAR = "1"
```

Thanks!

**Comment by nerdvegas** [comment]
Short answer, no! The package you're building never has its commands
evaluated, because, well, it isn't built yet! The intent of commands() is
to configure the target env in a way that includes that package. You can't
include a package you haven't built yet.

It would help to know what build info specifically you want access to in
env-vars. Something I've been wanting to do for some time is to have Rez
actually set a group of standard env-vars containing useful build info
(target dir, source dir etc). Right now that's left up to the build system
plugins, which is lame. Once we have this, I'd like to add an optional
'build_command' attribute to package.py, so that a package can specify how
it's built, meaning you could very easily support simple build.sh files for
example, which is useful in some cases (eg where the cmake becomes too
painful. It happens).

A

**Comment by nerdvegas** [comment]
Thinking further on this, I can see the need given your use case. Perhaps
we could add a commands_on_build() function for this purpose...

Another option is some tool that can interrogate packages in the current
env and/or the package currently being built. For example,
"rez-package-attribute --build-target name" would print to stdout the name
of the package currently being built.

Thoughts?

A

**Comment by ttanimura** [comment]
Hehe, I thought it was a bit of a silly question, but I thought I would ask anyway in case someone had done something similar. 

The main motivation behind the question was because documentation for some packages need to be built within Maya, because of reasons too boring to get into. I was thinking that each package could define a `BUILD_DOCS_IN_MAYA` env var and then have our cmake builds switch based on that.  

I also tried looking for `REZ_MAYA_VERSION` in the env, since the packages in question all depend on Maya, but it doesn't appear that the build happens inside the resolved env as cmake can't find that variable.

**Comment by nerdvegas** [comment]
Hey something else must be up, because the build definitely happens within
the resolved env! That's the whole point of rez-build.

There is a trap you may have fallen into, which happened to us as Method.
The cmake binary we were using in the build happened to come from a suite,
meaning that it runs within its own rez context, meaning that env-vars that
we expected to be there were not actually in the env that cmake was running
in! It all made sense but it caused confusion for some time.

**Comment by ttanimura** [comment]
A command in package.py would be ideal, but a separate utility to query the current env is a good idea. 

Along those lines, do you foresee any problems if we add our own `commands_on_build()` equivalent and `execfile('package.py')` to run it in this utility?

**Comment by ttanimura** [comment]
Cool, that is great to know about the cmake suite thing. I'm about to head out for the day, but will take a look tomorrow. Thanks for the speedy responses!

**Comment by ttanimura** [comment]
Sorry that execfile idea was silly - its not gonna work with rex of course. That's what I get for spitballing on my way out the door. Thanks again for the help - I've got env vars in cmake now ;)
