### ISSUE TITLE
Question: Managing variants

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#360]
Is there a way in Rez to define a set of variants outside of a package, and have multiple packages reference them? 

For example, lets say you have 30 Maya plugins that are each their own package. When a new version of Maya comes along, you have to go and add that new version as a variant to all 30 packages, which is time consuming. It would be great if there was a mechanism to define a common set of variants and share them across many packages.

Thanks!

**Comment by nerdvegas** [comment]
Hey Taisuke,

There is currently no 'include' mechanism for package.py files. If it were to exist I suppose the way to do it would be to configure some python path for rez where you could add such include files; then rez would massage PYTHONPATH so that you could perform a standard import in order to include the shared content. However, the imported content would have to be somehow hardened on the installed package - installed packages should be completely self contained, it's easy to see how changing an included variant list would break existing package installations if this weren't the case. 

It's a little clunky but this would work - maybe package.py files could contain specially formatted comments that perform code includes. Such comments would refer to python files stored in some configured directory. On install, the special comments are replaced by the matching file's contents. Eg:

    # /.../includes/maya_versions.py
    maya_versions = ["2016", "2016.5", ...]
    def gen_maya_variants(pkglist):
        return [(pkglist + [x]) for x in maya_versions]

    # maya plugin package.py
    #!INCLUDE maya_versions
    variants = gen_maya_variants(["platform-linux"])

On a related note: please post questions to the google group here: https://groups.google.com/forum/#!forum/rez-config

I'm gonna close this issue for now. Anyone know if github is providing forum support anytime soon..?
