### ISSUE TITLE
Question about suites versus full resolved contexts

### ISSUE THREAD

**Issue by ttanimura** [nerdvegas/rez#421]
Suites seem like a great way to expose package executables to non-Rez environments, but they seem error prone when used in conjunction with resolved contexts. 

Lets say I have a suite that exposes a number of tools in `foo-1.0.0`. If I use that suite within a context using `foo-2.0.0`, I still end up using the executables in `1.0.0`. Since the whole thing is transparent to the end user, it seems like it would create confusion, especially since suites could change under you while inside a resolved context.

Wouldn't it be safer to put users inside a resolved context, with each package exposing its tools using env vars? You would also get the added benefit of being able to access any modules and other bits each package defines. 

But I'm pretty new to suites to perhaps I'm thinking about them the wrong way.

**Comment by nerdvegas** [comment]
Heya,

First, be aware of this setting:
https://github.com/nerdvegas/rez/wiki/Configuring-Rez#suite_visibility

Second: When you are in a context, anything on PATH in that context takes
precedence over suites. Indeed this is necessary, otherwise you end up in
an infinite loop - the tool wrapper in the suite puts you into the context,
if the suite wrapper still took precedence when inside the context, that
would happen again, and so on. In fact you can see this in practice - if
you list a tool in package.py 'tools' that doesn't actually exist, then
when you try to invoke it via a suite, you'll hit this infinite loop.

I'm not sure what you meant by:
"""If I use that suite within a context using foo-2.0.0, I still end up
using the executables in 1.0.0.""" ?

Any tool that you use that is on PATH will be picked up before anything
from the suite, because the suite's bin path should be appended to PATH at
this stage.

"""Wouldn't it be safer to put users inside a resolved context, with each
package exposing its tools using env vars"""
I don't follow. The tool wrappers in a suite put you into that context,
then run the tool. Once you're inside a context, setting env vars for tools
has no relevance - you just run whatever binaries are visible on PATH.

If you use a tool from a suite when within a context, the context has no
relevance whatsoever, the tools run standalone. Suites are collections of
contexts - each too wrapper just boots you into the associated context and
runs the tool inside it.

Hth
A

**Comment by ttanimura** [comment]
Thanks for the info. I guess the part that i'm tripping up on is this:

> If you use a tool from a suite when within a context, the context has no relevance whatsoever, the tools run standalone.

Lets say that `foo-1.0.0` has tools `tool_a` and `tool_b`, and we put them in a suite called `blah`. `tool_b` is then removed in `foo-2.0.0`. If I resolve a context with `foo-2.0.0` that also adds the `blah` suite, then `tool_b` will be available on `$PATH`, even though it may do things that aren't compatible anymore.

I guess its a matter of carefully managing what suites get used inside of contexts? This whole thing came up as we try to figure out how to set up default contexts for shows/shots, and where suites would fit into that.

**Comment by nerdvegas** [comment]
"""... then tool_b will be available on $PATH, even though it may do things
that aren't compatible anymore."""

Yes, because tool_b is coming from the suite, not the context.

When you're using a mixture of contexts and suites like this, it's up to
you to manage what to do if and when some tools come from the suite while
others come from a context. The suite is the constant factor here, it's
just making available the tools you put into it, regardless of what an
unrelated current context is doing. There's no special case for when you're
in a context which is using package(s) that tools in a suite are also
using. You're just gonna get whatever is on PATH after all.

Hth
A

**Comment by ttanimura** [comment]
Yep, makes sense. Thanks :)
