### ISSUE TITLE
late binding  and memcache issue

### ISSUE THREAD

**Issue by fnaum** [nerdvegas/rez#437]
Hi,

We noticed an issue with the late bindings and memcache.
We are aiming to use the late binding to do some conditional requires i.e

```
name = 'animal'
version = '1.0.0'
uuid = '7ef292ad-a58e-4f54-8e43-620ae1914626'

description =     """  Just a test   """

@late()
def requires():
    import os
    if os.environ.get('TEST', 0):
        return ['python-2.6']
    else:
        return ['python-2.7']
```

Then 
```rez-env animal``` gets `python2.7` in the evironment
but 
```
export TEST=1 
rez-env animal  
```
still gets  `python2.7` instead of `python2.6`
if we run
```rez-env animal --no-cache``` it works fine, bringing `python2.6` into the solved evnironment.

I'm guessing that the key for memecache is set before the @late is excetued but it should be done after that. I'm going to have a look at the code
Can someone double check this?

**Comment by nerdvegas** [comment]
Yeah resolve caching is not compatible with late-binding requires
attributes.

The resolve caching mechanism basically says, "if cached resolve X uses
packages [Y], and no new versions of [Y] are visible (ie installed or
released) since the last cache time, then X can be reused." This test is
cheap and fast, it costs only len(Y) file stats to perform.

To get this to work with late-binding requires attributes, this cheap test
wouldn't be enough. Instead, all package definitions with late-bound
requires would have to be re-evaluated, and the state of these evaluations
would also have to be stored into the cache key (for eg, a hash of the
requirements of each visible package).

It's possible to add this support (if not complicated), but turning it on
would slow down resolve caching in general, and possibly a lot depending on
the package counts you're running with.

I don't think there's an easy solution to this one, but I'm all ears.

A

**Comment by fnaum** [comment]
Hi Allan, 

Thank you so much for your quick response.
I brought you answer for discussion with the team that needs this feature, and also had a look at the code with the debugger to check when this late() functions get evaluated, and you are right, it does not seems that there would be an easy solution for this problem, at least none that would not affect the performance of the caching functionality.

For now, since what they have modelled with this conditional requires is experimental they say they are ok paying the cost of not using the cache.
If we start using this feature more and more or if the resolve time without the cache gets unbearable we will have a look at possible compromises.

I'll close this issue for now. And reopen it we ever need this feature.

**Comment by nerdvegas** [comment]
Cheers Fede, it's good to be aware of these use cases.

A
