### ISSUE TITLE
Issue with environment using "ResolvedContext.execute_command" on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [nerdvegas/rez#441]
It looks like the environment used to spawn the subprocess in `ResolvedContext.execute_command` is not being primed correctly: 

``` python
import os
import sys

sys.path.append('C:\\Program Files\\rez\\Lib\site-packages\\rez-2.13.0-py2.7.egg')

from pprint import pprint
pprint(sorted(os.environ.keys()))

environment = {'MY_CUSTOM_VARIABLE': 'MY_CUSTOM_VALUE'}
from rez.resolved_context import ResolvedContext
context = ResolvedContext(['python'])
context.execute_command(
    'python -c "from pprint import pprint;import os; pprint(sorted(os.environ.keys())); import random; random.Random()"',
    parent_environ=environment)
```
and the output trimmed for the first `os.environ` print :

```python
[ ...
 'PROGRAMDATA',
 'PROGRAMFILES',
 'PROGRAMFILES(X86)',
 'PROGRAMW6432',
 'PROMPT',
 'PSMODULEPATH',
 'SYSTEMDRIVE',
 'SYSTEMROOT',
 'TEMP',
 'TMP',
 ...]
['COMSPEC',
 'PATH',
 'PATHEXT',
 'PROMPT',
 'PYTHONHOME',
 'PYTHONPATH',
 'REZ_ARCH_BASE',
 'REZ_ARCH_MAJOR_VERSION',
 'REZ_ARCH_MINOR_VERSION',
 'REZ_ARCH_PATCH_VERSION',
 'REZ_ARCH_ROOT',
 'REZ_ARCH_VERSION',
 'REZ_PATH',
 'REZ_PLATFORM_BASE',
 'REZ_PLATFORM_MAJOR_VERSION',
 'REZ_PLATFORM_MINOR_VERSION',
 'REZ_PLATFORM_PATCH_VERSION',
 'REZ_PLATFORM_ROOT',
 'REZ_PLATFORM_VERSION',
 'REZ_PYTHON_BASE',
 'REZ_PYTHON_MAJOR_VERSION',
 'REZ_PYTHON_MINOR_VERSION',
 'REZ_PYTHON_PATCH_VERSION',
 'REZ_PYTHON_ROOT',
 'REZ_PYTHON_VERSION',
 'REZ_RAW_REQUEST',
 'REZ_REQUEST',
 'REZ_RESOLVE',
 'REZ_RESOLVE_MODE',
 'REZ_USED',
 'REZ_USED_IMPLICIT_PACKAGES',
 'REZ_USED_PACKAGES_PATH',
 'REZ_USED_REQUEST',
 'REZ_USED_REQUESTED_TIMESTAMP',
 'REZ_USED_RESOLVE',
 'REZ_USED_TIMESTAMP',
 'REZ_USED_VERSION',
 'REZ_VERSION']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "K:\Packages\ThirdParty\python\2.7.13.rf1\platform-windows\arch-AMD64\Lib\random.py", line 885, in <module>
    _inst = Random()
  File "K:\Packages\ThirdParty\python\2.7.13.rf1\platform-windows\arch-AMD64\Lib\random.py", line 97, in __init__
    self.seed(x)
  File "K:\Packages\ThirdParty\python\2.7.13.rf1\platform-windows\arch-AMD64\Lib\random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly
```

So the random error is described in that thread: https://lists.gt.net/python/dev/879269, the TLDR is that on Windows *%SystemRoot%* must be defined which it is in the original calling script but not in the resolved environment used by  `ResolvedContext.execute_command`, I can't even see my `MY_CUSTOM_VARIABLE` variable.

Is there a way to update the context environment before invoking `execute_command`?

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Hey Thomas,

It looks like you've actually hit an extremely similar bug to what Fede
found and fixed just recently. I tested your code above and I didn't see
MY_CUSTOM_VARIABLE in the output either. I will fix this at the same time I
merge Fede's very similar fix (will add tests also).

Wrt SYSTEMROOT missing, not sure about this Windows behavior. You are
providing a environ dict explicitly, I don't know what expected behavior is
on Windows if running a python subprocess and providing the 'env' arg (as
the execute_command() code is doing). You could try using a copy of
os.environ as parent_environ.

Cheers
A

**Comment by KelSolaar** [comment]
Hey Allan,

> You could try using a copy of os.environ as parent_environ.

It is actually the first thing I tried and I still get the same output, I'm assuming that the info is lost -in-translation somewhere in the chain.

Cheers,

Thomas

**Comment by nerdvegas** [comment]
Hey Thomas, I've found the problem, fix coming soon. Seems a bug has always
been present that doesn't actually set anything in the parent_environ into
the target env dict. I don't think execute_command() is used much (it isn't
the same as execute_shell()) so that may be why this bug has survived for a
long time..

A

**Comment by nerdvegas** [comment]
Fixed, see release 2.13.1.
A

**Comment by KelSolaar** [comment]
Thanks!

**Comment by KelSolaar** [comment]
Confirming the issue is solved on my end, closing the ticket!

Thanks :)
