### ISSUE TITLE
cmake-3 won't install files

### ISSUE THREAD

**Issue by nerdvegas** [nerdvegas/rez#450]
Not yet sure of the root cause, but we have a repro where cmake-3.8.0 on CentOS-7 does not install the built files. I * think* this is specific to the cmake version, but OS could also be a factor.

**Comment by jlgerber** [comment]
I am using cmake 3.5.2 on os x and i have noticed that when i build hello_world, only the rxt file and the package.py file get installed. Neither the bin/hello or the python/hello_world.py get installed.

**Comment by nerdvegas** [comment]
Hi, yeah this has been reported before, seems to be some cmake-3 change. I'll look into this soon.

Thx, A

**Comment by smaragden** [comment]
Might be related to the cmake policy CMP0037. That stops you from overriding the install target. This can be disabled by setting:
cmake_policy(set CMP0037 OLD)

This is a temporary solution and my guess is that tools like Rez should probably use the cmake server functionality since v3.7.
https://cmake.org/cmake/help/v3.7/manual/cmake-server.7.html

**Comment by jlgerber** [comment]
@smaragden, unfortunately, adding this command did not fix my problem on os x.

**Comment by bfloch** [comment]
This is what cmake spits out with version 3.9.0
~~~
CMake Error at [...]/rez-2.13.1.tbe1/lib/python2.7/site-packages/rez-2.13.1.tbe1-py2.7.egg/rezplugins/build_system/cmake_files/RezProject.cmake:21(add_custom_target):
  The target name "install" is reserved or not valid for certain CMake
  features, such as generator expressions, and may result in undefined
  behavior.
Call Stack (most recent call first):
[...]/rez-2.13.1.tbe1/lib/python2.7/site-packages/rez-2.13.1.tbe1-py2.7.egg/rezplugins/build_system/cmake_files/RezBuild.cmake:95 (rez_project)
  CMakeLists.txt:5 (include)
~~~

@smaragden 's suggestion fixes it, you just need to use `SET` instead of `set`. 
~~~
cmake_policy(SET CMP0037 OLD)
~~~

**Comment by venukris** [comment]
I faced the same issue on osx. I figured the culprit to be `add_custom_command(install)` in RezProject.cmake (removing it fixed the issue for me) -https://github.com/nerdvegas/rez/blob/master/src/rezplugins/build_system/cmake_files/RezProject.cmake#L21

I'll admit I have no knowledge of cmake, so I have no idea what that line does and if I should be removing it at all. Maybe there is an elegant fix for this.

**Comment by nerdvegas** [comment]
Thanks for that info Venu.
A

**Comment by hdd** [comment]
Hi there , just found myself with the same issue with cmake3
is there any fix planned or better stick with 2.8 ?

**Comment by nerdvegas** [comment]
Hi Lorenzo,

Please tell me your rez version when reporting issues!

Have you tried this recent release yet?:
https://github.com/nerdvegas/rez/releases/tag/2.17.1

Thanks,
A

**Comment by hdd** [comment]
Hi Allan, sorry was 2.17.0 .
I'll give immediately a shot at this patch release.
Thanks!
L.

**Comment by nerdvegas** [comment]
Closing as I believe this is addressed in https://github.com/nerdvegas/rez/releases/tag/2.17.1, please reopen if this is not the case.
