### ISSUE TITLE
Evaluation order of Requires list

### ISSUE THREAD

**Issue by jhollobon** [nerdvegas/rez#468]
Hi there,

I'm running Rez 2.14.1 under Windows 7, I've encountered some behaviour which strikes me as odd, and was wondering if I'm overlooking something.

Suppose I create a couple of packages, and name them 'A' and 'B'. They have no dependencies. They each append to PYTHONPATH, and the order of the paths matters to me. So the order in which the packages are evaluated matters.

Suppose I want package B to be evaluated first, and A second. Rez enables me to request the packages in a certain order, so I can do this at the command line:

$ rez-env B A

And I'll get the desired result (i.e. B is evaluated before A). So far, so good.

But suppose I create another package, called _Foobar_. It does nothing, but the package.py file contains this:

requires = ['B', 'A']

I would have expected that this requires list would be evaluated in the supplied order (just like it was at the command-line) and that I could run this:

$ rez-env Foobar

To get the same result as my previous command. But it appears that Rez sorts the 'requires' list into **alphabetical order**, before evaluation. So, due to the package names I used, package A gets evaluated first, and package B second. The package evaluation order has been reversed.

Is this the expected behaviour? Apologies if I'm overlooking something obvious, I'm relatively new to Rez. I couldn't find this mentioned on the Wiki, or this Issues list. Any thoughts/suggestions would be welcome.

Thanks,
Jeremy

**Comment by nerdvegas** [comment]
Hey Jeremy,

First, apologies RE the lack of docs on this, I need to add more to the
Wiki wrt dependency resolution.

In short, yes this is expected behaviour. Only the package order in the
original request affects command evaluation order. Relying on the order of
`requires` in any given package wouldn't be very obvious - a typical solve
involves hundreds of packages, and it isn't really possible to know exactly
when a package will be pulled into the solve, so predicting the evaluation
order for any given solve would be almost impossible. Now having said that,
I don't recall why the requirements are put into alphabetical order(!), at
a guess I'd say they get converted to a set at some point for performance
reasons, and the sort just guarantees a deterministic result (which is
important - you don't want the same request to return different results
when no packages have changed).

There is definitely the idea that if A and B are unrelated (ie have no
common dependencies) then their order of evaluation shouldn't matter.
However there are always exceptions to the rule, and you may be interested
in this feature:
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#pre_commands

Hth
A

**Comment by jhollobon** [comment]
Thanks heaps for your reply, that is super helpful. That explanation makes good sense, and gives me loads of ideas for better ways I could handle this situation.

Jeremy

PS: Congrats on the great work.
