### ISSUE TITLE
rez-bind module.bind(): Can I return multiple package versions?

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#502]
I've been digging through the source to learn how to write a rez-bind module, and I'm stuck on one point.

I understand that the build-module function ``build()`` can return multiple *variants* of the *same version*. Is it possible for rez-bind to also discover *multiple versions*? Is there a workflow you guys use to discover all versions/variants of a package at once?

Say for instance I'd like to discover maya versions 2016, 2017, and 2018

`bind/maya.py`
``` python
from rez.package_maker__ import make_package
import glob


def bind( install_path, version_range=None, opts=None, parser=None ):
    # we'll pretend no other os exists
    maya_paths = glob.glob('/usr/autodesk/maya[0-9][0-9][0-9][0-9]*/bin/maya')

    with make_package( 'maya', install_path ) as pkg:
        pkg.name     = 'maya'
        pkg.version  =                                     ## <==( list of versions (?) )
        pkg.variants = [
            ['platform-linux','arch-amd64','os-arch'],
        ]

    return pkg.installed_variants
```

Thanks very much, and sorry

- Will

**Comment by instinct-vfx** [comment]
First up: I think for general questions the mailing list may be a better place to post (https://groups.google.com/forum/#!forum/rez-config)

Here is what we do in our 3d Studio Max package. Note: I have no idea if this is best practice, but it works:

```
    def make_root(variant, path):
        pass

    for version in VERSIONS:
        with make_package(PKG_NAME, path, make_root=make_root) as pkg:
            logger.info("Creating rez-package for 3dsmax {}"
                        .format(version))
            pkg.version = version
            pkg.uuid = UUID
            pkg.authors = ["Mackevision"]
            pkg.description = ("Package of 3dsmax version {}"
                               .format(version))
            pkg.variants = VARIANTS

            pkg.commands = textwrap.dedent(commands_str.format(
                                               version=version))

        installed_variants.extend(pkg.installed_variants or [])
        skipped_variants.extend(pkg.skipped_variants or [])
```

**Comment by willjp** [comment]
Thank you so much! Oh god, of course, it's just a list! Sorry, I should have come to that conclusion on my own.

That's great! I did not realize there was a mailing list, I'll subscribe and check/ask any further questions there. Have a great day,

Will

**Comment by nerdvegas** [comment]
Hi Will,

Bind modules are something I'd like to deprecate actually. They were only
ever added as a quick way to interface existing installed software into rez
for testing purposes.

IMO the better way to do this now is to use the new programmatic aspects of
the package definition, as shown in this example package:
https://github.com/nerdvegas/rez-recipes/blob/master/python/_native/package.py

This is an example of a "native" python package - ie, one that exposes an
existing software installation to rez, rather than a new separate
installation. You can read up on any of the features used here:
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide.

Apologies if you've wasted much time on the bind route. Let me know if you
have questions or if you think the native package approach won't work for
some reason. I haven't had the time yet to formally replace all existing
bind modules with equivalent native packages (and then deprecate bind
modules completely), but that's my longer term intention at the moment.

Cheers,
Allan

**Comment by nerdvegas** [comment]
Native packages are just normal packages, but are designed to interface
with already-installed software. eg:
https://github.com/nerdvegas/rez-recipes/blob/master/python/_native/package.py

In terms of multiple versions: I've realized the same thing - ie that
package definitions need a way to express that they may be able to build to
multiple versions. In that case I'd say that rez-build might do something
like this:

    ]$ rez-build
    This package can build multiple versions of the software; you need to
use --version to specify. To see a list of potential versions to build, use
--list-versions.

If you mean an already-installed package that can manage multiple versions,
that actually already exists, and is used (I believe) extensively by Luma
studios. It's a different kind of package.py called a "multi-version"
package, but it isn't well documented because it doesn't have widespread
use.

A

**Comment by LocksmithAnimation** [comment]
Hey @nerdvegas! I was about to implement a series of bind scripts for managing locally-installed software, and came across this thread. Are you still intending to deprecate the bind methodology?

If so, I'll head straight on down a native package approach -- I can see how this would work fine as well.

Thanks!
 -- Brian --
