### ISSUE TITLE
rez-bind timestamps, and rez-env --time

### ISSUE THREAD

**Issue by willjp** [nerdvegas/rez#511]
This is not a bug, but potentially problem depending on your intentions for `rez-env --time`. I'm not sure if this should even be in the issue tracker, or the google-pages.

* When using `rez-bind`, the resulting packages are timestamped at the time that rez-bind was run.
* If you use `rez-env --time <timestamp>`, the time that software was bound will affect which packages are allowed to be used.

On one hand, this is necessary for reproducing the exact same rez-build environment. On the other hand, a rebuilt workstation with a freshly rez-bound python, platform, os, ... etc would not be allowed to step back in time to create the same build. 

I don't really have a good solution for this, if a solution is even needed. I just thought I would raise it in case you guys had any ideas.

**Comment by nerdvegas** [comment]
So, rez-bind will be deprecated at some point, in favor of 'native'
packages - which are just normal packages, but ones that make use of newer
features such as early binding in order to wrap system-installed software.
But, your point still stands.

I don't think there's a simple solution to this. Although believe it or not
there is a way around it - you can use 'package filters' to set a timestamp
on all packages _except_ a nominated list. That's a very manual approach
though and I doubt it would be practical.

Another idea would be to add ability to nominate certain package repos as
timeless, ie ignore all timestamps in those packages. But for the amount of
work this would be in relation to the payoff, I don't see this being done
anytime soon.

A

**Comment by willjp** [comment]
Thanks very much! I haven't played with package filters yet, and this seems like a pretty good excuse to get my hands dirty :) 

If I understand correctly I could combine both ideas. 
1. separate my rez-bound packages into their own repo
2. produce a list of packages in all repos EXCEPT the rez-bind module repo
3. use that list as an exception to a package filter.

Right now I've been running a setup script for users that runs rez-bind, so if anything is found those packages have their timestamp set to unix-epoch.

I think I'll close this. It's not really an issue. I'm sorry, I should have posted this on the google group.
