### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#55]
Hi,

I'd be interested in providing support for Windows. 

Having briefly looked through your manual and source-dived part of your 2.0 release, I've gathered that much of Rez is built upon bash, which I can imagine being a challenge if ported to cmd.exe.

Is there anything else you think I should be aware of? Which part of your codebase would you recommend I get started with?

### Edit

In an attempt to make this issue referable to newcomers and have them get up to speed more quickly, I'll collect some relevant links here.

* [Windows Fork](https://github.com/instinct-vfx/rez)
* [Rez Usergroup](https://groups.google.com/forum/#!forum/rez-config)

Best,
Marcus

**Comment by mstreatfield** [comment]
Hello @nerdvegas, @mottosso, @instinct-vfx and @chadrik,

I got Windows and OSX support up and running at work on Friday and am now able to `rez env` on both operating systems.

For OSX there really wasn't much to do as it pretty much 'just worked' but I'll make a pull request with the changes next week.  I can also `rez build` on OSX (but have not tested `rez release` or other features).  Unit tests pass.

WIndows was a little tricker.  
* There are changes to the `install.py` script which are fairly trivial and I'll make a pull request for these next week too - mainly some path handling changes for virtualenv.
* I created a `cmd` shell plugin to work with the Command Prompt and to replace the existing `Windows` plugin.  Currently there is no shell detection so this is the default.  I'll include this in the pull request.  It doesn't include some of the more advanced features of Bash and SH plugins but gets us going.
* The API for shell plugins is really unclear.  It wasn't obvious what methods the plugin should implement, and the inheritance between existing plugins is broken in some cases.  `UnixShell` ended up being a better base class than the intended `Shell`.  I think it would be good to make a pass at refactoring this before looking at other Windows shells such as PowerShell.
* Coloured output doesn't work - the control characters are printed.  According to the `colorise` documentation we are doing right so not sure what is wrong there.
* There is a bug in the `config` module and the handling of `~` in config values related to Python's `os.path.expanduser` method (read the documentation on this method to see how it is implemented different across operating systems to better understand this problem).  When getting the implicit packages from the config file (which are all weak), the `~` is being expanded, so the implicit package becomes `C:\Users\platform-osx`.  This isn't a problem on Linux/OSX due to the different implementation of `os.path.expanduser`.  My current thinking is to update the `config` module so only parts of the schema defined as a path (not just `Str`) are expanded.  Thoughts? 
* I haven't tried building/releasing yet.  I expect there to be more problems.
* The unit tests don't pass.  In part this is due to the `rez.vendor.sh` module which doesn't work on Windows, and various temp file issues.  I'll try and tackle those.
* I need `{system.home}` as in issue #153 so will add this.

But I'll make a pull request with the changes I have so far as it's definitely a step forward and things 'work'.  Hopefully this will enable someone else to pick up some of these other problems (such as the colour) as we are no longer starting from scratch.

It was actually pretty rewarding to get this up and running in such a short space of time (<4hrs) given I thought it's be pretty daunting.  I haven't seen comments/commits saying others have already done this, so hopefully I'm not doubling up!

**Comment by chadrik** [comment]
nice work!  thanks, Mark.




-chad





—

**Comment by nerdvegas** [comment]
Mark, that's awesome news, thanks a lot.

**Comment by mstreatfield** [comment]
In an ideal world, I'd be able to use the same `rezconfig` file for both Linux, Windows and OSX installs.

However this doesn't quite work.  For example, the `prompt` value is different between platforms - on Linux `>` is fine, but on Windows (at least for the Command Prompt) this must be `$G` as `>` is not directly supported.  Other values such as `tmpdir` are affected in a similar way.

What do you think the best way of handling this is?  I could:

1. add a section at the end of the `rezconfig` file for operating system overrides and update `config.py` to respect this, so:

    prompt: >
    windows:
      prompt: $G
      tmpdir: C:\temp

2. or make platform specific keys that would override the default ones, so:

    prompt: >
    prompt_windows: $G

Obviously I could just install rez separately for the different platforms, but that seems to be a missed opportunity.

**Comment by chadrik** [comment]
convert the rezconfig file to a python config file like celery's and sphinx's?

**Comment by mstreatfield** [comment]
I have created pull request 159.  Take a look and let me know what you think.

Tests pass (ish - I've had to skip a few) and the Windows Command Prompt isn't 100% supported but it does work.

**Comment by nerdvegas** [comment]
We have Windows support!
