### ISSUE TITLE
Rez env to version based on suffix?

### ISSUE THREAD

**Issue by assumptionsoup** [nerdvegas/rez#578]
Is there a way to rez env to a version that requires a suffix e.g. `rez env mypackage-2*dev` that would resolve to `mypackage-2.1.1.dev`?

**Comment by JeanChristopheMorinRodeoFX** [comment]
@assumptionsoup That can be achieved with the `--include` argument on the rez-env command. Something like `rez-env mypackage --include rez env mypackage-2*dev`

**Comment by assumptionsoup** [comment]
That doesn't appear to exclude packages without the dev prefix.  In my tests (on windows) `mypackage-2.2.0` trumps `mypackage-2.1.0.dev`. I'd like to only include results with the given prefix.

**Comment by bpabel** [comment]
Could you reverse it?  `mypackage-dev.2.1.0`

**Comment by assumptionsoup** [comment]
I'm using these suffixes to determine what "type" of release is done. Putting the prefix first interferes with rez's normal version resolution.  With `mypackage-dev.2.1.0` and `mypackage-5.0.0` the dev version will resolve first because letters are higher than numbers.  I'm not thrilled that `mypackage-2.1.0.dev` resolves above `mypackage-2.1.0`, but it's better than version 2 being picked up before version 5.

**Comment by assumptionsoup** [comment]
Currently I'm marking packages in my local release area with "dev". Released packages have no prefix. Beta packages released on the server have "beta" suffixes. The idea is that it's very clear what kind of package this is, and that these suffixes would give us better control over what kind of package to resolve to. We are using --exclude to exclude beta releases. This gives us control over "local" vs "beta" vs "release" packages without needed to resort to modifying the package paths.

However, when developing, it would be nice to only pick up development versions of the things I'm developing. When I'm developing, I don't care if someone else has released a slightly newer version to the server. I don't want to accidentally pick that up. I _could_ lock my rez env to a specific version, but I'd rather say "I'm developing package x y z. I for these (and only these) I only want to pick up the local version." Dependencies can resolve from anywhere.

I think the best way to do this would be to resolve based on suffix. But it looks like rez is lacking in this one specific way. It feels like a bit of an oversight to be honest. We have so much control over version resolution, except for the ending. I know that's because this is because of semver, but it still feels a bit strange.

It doesn't seem that rez package path was designed to help with these kind of "channels" where a version in one path should trump a higher version in a different path.  Suffixes seemed like  good idea.

Thinking this through, `mypackage-dev.2.1.0` would be picked up before release versions, and `mypackage-2.1.0.beta` would work for the server though I wish that `mypackage-2.1.0` trumped `mypackage-2.1.0.beta`.  So I can work around this with your suggestion.  It does feel a bit.. hacky though.

**Comment by assumptionsoup** [comment]
Actually, that won't work. If the dev package is a dependency of another package `mypackage-dev.2.1.0` is significantly different than `mypackage-2.1.0`. You'd have to change the requires on the consuming packages, which is nasty.  Changing a requirement in package.py might be expected when developing a library. `mypackage-2.1+<3` becomes `mypackage-2.2+<3` - but changing the requirement to `mypackage-dev.2.2+<3` would be nasty because if this gets released, it's going to resolve to the wrong package.

**Comment by nerdvegas** [comment]
Rez won't let you do something like `rez-env foo-*dev`, because version
numbers are not treated syntactically like this - version comparisons are
not like string comparisons. Versions are hierarchical numeric objects.
Supporting both string-like comparisons and semantic comparisons would be
confusing and would almost certainly lead to ambiguous cases. Package
filters on the other hand can do this, because there are different types of
those, and they can be thought of as a preprocessing step before the solver
does its thing. I don't know what impact string-like version comparisons
would have on the solve step, but I don't think it'd be good.

""'When I'm developing, I don't care if someone else has released a
slightly newer version to the server"""

I agree with this, and it's come up before. I think a `--local-precedent`
or similar flag would to the job - ie, if any versions of a package are
local, then only consider those local versions of that package (ignore all
others).

You can kind of do what you want with package filters, however it's clunky
because you need to take every package into account. For example, if you
had local packages A and B, then you could go `rez-env --exclude A-* B-*
--include A-*dev B-*dev`.

Hth
A

**Comment by assumptionsoup** [comment]
I totally agree. That flag is exactly what I'm looking for. Looking for control over the suffixes was more of a work-around.  I did notice that I could control this with package filters, but I found that too clunky, as you said. At that point it's simpler to specify the exact local version.  A `--local-precedent` flag would solve this problem completely.

**Comment by nerdvegas** [comment]
Closing in favour of https://github.com/nerdvegas/rez/issues/652
