### ISSUE TITLE
Custom build arguments broken since 2.26.0

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#587]
This occured and is reproducible for me on windows 7.

In 2.26.0 cli/build.py was changed from:

```
    if clss:
        if len(clss) == 1:
            cls = clss[0]
            cls.bind_cli(parser)
        else:
            types = [x.name() for x in clss]
            parser.add_argument(
                "-b", "--build-system", dest="buildsys", type=str, choices=types,
                help="the build system to use.")
``` 

to:

```
    if clss:
        if len(clss) == 1:
            cls_ = clss[0]
            title = "%s build system arguments" % cls_.name()
            group = parser.add_argument_group(title)
            cls_.bind_cli(group)

        types = [x.name() for x in clss]
    else:
        types = None
```

This change leads to custom build arguments (defined in parse_build_args.py) to be visible when calling `rez-build --help` as an additional group at the end of the argument help (which i assume is the intention here) but the corresponding environment variables are not created in the build environment.

This seems to be due to `cls_.bind_cli(group)` only passing on the group rather than the parser which breaks the argument parsing in custom.py

**Comment by lambdaclan** [comment]
Hello Thorsten,

This indeed seems to be a bug, it can easily be remedied by using the `parser._action_groups` private method to access the parser's groups. 

Simply passing the parser object (LazyArgumentParser - subclass of normal ArgumentParser) instead of the group object (AgumentParserGroup) would also work but the extra arguments will be in the main help menu (group item will be ignored).

![Selection_001](https://user-images.githubusercontent.com/47409392/55057063-72f80f80-50ab-11e9-83ff-00fe5c6f0df3.png)

This means that we should pass the parser object to `cls_bind_cli` like we used to before 2.26 but then get the argument group object to insert the extra arguments defined in the  parse_build_args.py file on that instance (enabling the custom group when using --help) and finally set the attribute to the parser object instead of the argument group object. 

![Selection_002](https://user-images.githubusercontent.com/47409392/55057452-9b343e00-50ac-11e9-8d11-9815896e7e17.png)

I have already got it working locally so we can open a PR. 👍

**Comment by nerdvegas** [comment]
PR please, if it isn't there already :)

A

**Comment by lambdaclan** [comment]
@instinct-vfx @nerdvegas I have just added a PR for the issue :+1:  more incoming!

**Comment by nerdvegas** [comment]
fixed in https://github.com/nerdvegas/rez/releases/tag/2.30.0
