### ISSUE TITLE
[Feature] Support for Or-package

### ISSUE THREAD

**Issue by mottosso** [nerdvegas/rez#643]
### Goal

Support requirements that depend not not on only a range of different versions, but also a range of different packages.

### Motivation

It's rare for this to have been an issue, I've only encountered it once so far for a very specific case. Qt.py requires either PySide, PySide2, PyQt4 or PyQt5, and yet there is no way to make this request; it can't depend on all, and it can't depend on none.

However, it dawned on me that this can also solve #21 which would be great, and could potentially squat two flies with one stone.

### Implementation

Syntax is still not clear, but spontaneously I found the `|` symbol quite intuitive.

From your `package.py`

```python
requires = [
  "pyyaml-2.4",
  "six-1.1",
  "PySide-1.2|PyQt4-4.7|PyQt5-5.7.1|PySide2-5.11"
]
```

And from the command-line.

```bash
$ rez env mayapy|python
```

Where the first package found is picked.

As an added bonus, we'll also (finally) be able to account for #21 by adding a "null" package that does nothing.

```python
requires = [
  "packageA-1.2|null"
]
```

Now both `packageA-1.2` and `null` are equally acceptable. If `packageA-1.2` isn't found, it would behave as though it was optional and not break the solve.

**Comment by nerdvegas** [comment]
There are already two ways to largely achieve the goal here.

The first is variants. The downside to variants in this case is that you
would be installing 4 different copies of the package payload, even though
there's no difference between them. Had this been a compiled package
though, variants would probably have been the best way to achieve this (by
way of example).

The second approach, is imo is arguably better, is to use a late-bound
requires:

    @late()
    def requires():
        variants = []
        if "PySide" in request:
            variants.append(["PySide-1.2"])
        ...
        return request

The problem with the Or'd syntax in your example is that there's no way to
control which dependency you're actually going to get. For example, the
PyQt5 dependency isn't invalid just because PySide might be in the request
- there's nothing special about these packages as far as rez is concerned,
and they don't conflict with one another. Using a late-bound requires fixes
this problem - the behaviour of the package is clear that, if PySide is in
the request, then the PySide dependency becomes activated.

Technically it may be possible to get or'd requires to work, but I'm fairly
sure it's going to be pretty difficult to do, and I'm concerned that this
feature, in combination with variants, will cause some quite complicated
problems. Or'd package requirements would require significant updates to
the solver. Right now I would categorize this feature request as possibly
nice to have, but at the cost of potentially significant complexity, and
significant development cost. Imo there are other features we could work on
that would bring greater benefit to the project, at lower dev cost.

A

ps - The example syntax given doesn't work, because even though it doesn't
look like it, what you have there is a valid standard version range.
PySide-1.2|PyQt4-4.7
== (PySide-1.2 OR PySide-PyQt4-4.7).

**Comment by nerdvegas** [comment]
*Example code should have read 'return variants'
