### ISSUE TITLE
[Bug] getenv throws RexUndefinedVariableError instead of None for undefined variables

### ISSUE THREAD

**Issue by ruzette** [nerdvegas/rez#646]
`getenv` throws a `RexUndefinedVariableError` instead of returning `None` inside the commands/pre_commands functions. 

According to [Package Commands](https://github.com/nerdvegas/rez/wiki/Package-Commands#getenv) page, function should return `None`.

### Information:
Running `rez` version `2.23.1` 
```
~platform==linux  (implicit)
~arch==x86_64     (implicit)
~os==centos-7     (implicit)
```
### package.py
```
name = 'package'

version = '999.0.0.dev'

def commands():
    # Add LD_LIBRARY_PATH if environment variable has been set.
    # Otherwise, do not add it.
    if getenv('LD_LIBRARY_PATH'):
        env.LD_LIBRARY_PATH.append('/path/to/package/lib')
```
### Error
```
$ rez env package
14:25:24 ERROR    RexError: Failed to execute </home/user/packages/package/999.0.0.dev/package.py:commands>:
Traceback (most recent call last):
  File "/home/user/packages/rez/2.23.1/platform-linux/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/utils/sourcecode.py", line 215, in exec_
    exec pyc in globals_
  File "</home/user/packages/package/999.0.0.dev/package.py:commands>", line 23, in <module>
  File "/home/user/packages/rez/2.23.1/platform-linux/lib/python2.7/site-packages/rez-2.23.1-py2.7.egg/rez/rex.py", line 274, in getenv
    "Referenced undefined environment variable: %s" % expanded_key)
RexUndefinedVariableError: Referenced undefined environment variable: LD_LIBRARY_PATH
```
### Relevant code
Digging through the tag `2.23.1`, the error is being thown in the line below. Same code also exists in the `master` branch.
https://github.com/nerdvegas/rez/blob/568f38cfc52122d769c1950adb9ca1d0075f6d62/src/rez/rex.py#L267-L274

### Suggestion
- Edit the wiki to indicate that `getenv` throws the error when the environment variable is missing, or;
- Return `None` when `KeyError` exception occurs.

**Comment by nerdvegas** [comment]
Hi Ruzette,

Good find. Looking into it though, I think it's actually the docs that are
wrong. There's even a test that verifies current behaviour:
https://github.com/nerdvegas/rez/blob/master/src/rez/tests/test_rex.py#L275

I'll update the docs. If you need to check for an evar existing (or more
specifically - whether it has been defined in the current rex execution
instance), you should use either the `if 'FOO' in env` form, or
https://github.com/nerdvegas/rez/wiki/Package-Commands#defined.

Let me know if this was causing any problems otherwise.

Thx
A
