### ISSUE TITLE
Using resolved context in package commands

### ISSUE THREAD

**Issue by bsilvaLS** [nerdvegas/rez#687]
Hello! I have a Rez package that deploys a Python API for getting shared settings called `project_settings`. I have another Rez package that requires that `project_settings` package.

In some cases, I'd like to be able to use the API from `project_settings` in the `commands()` function of the second package. I want this to happen at rez-env time, not build time. Is there a way to run `commands()` or `post_commands()` in the resolved environment for the package?

Then I could leave it in the `requires `attribute, which I want to do anyways (for other launch scripts, etc.)

I can't seem to find a way to do that. Is this possible?

**Comment by nerdvegas** [comment]
That isn't possible because it's a catch-22 - packages' "commands" are used
to configure the target environment, and before the target environment is
configured, you can't use the packages that are in it.

The code in "commands" is converted into the target shell language and then
executed. To be able to use another package's API in your own 'commands'
would actually be very complicated and inefficient. Effectively you'd have
to do this shell conversion and creation of target environment separately
for every package (cumulatively), so that each 'commands' is then being run
in the properly configured env for all packages preceding it (preceding ==
reverse dependency order). Tbh I don't see rez ever doing this, the runtime
cost alone would be high (a resolve containing 100 packages would configure
+ create 100 subshells in succession).

It may help if you explain what you're trying to do. There may be another
way to go about it.

Thx
A

**Comment by bsilvaLS** [comment]
Yeah, I can see how that would cause huge inefficiencies. I was thinking it would be nice to be able to operate in the configured environment for all the required packages for this one package -- if there was some way to flag it so only this package triggered that breakup, could you avoid the mass inefficiency of doing that for all packages? But it seems like this could also change the logic of the resolve if not done carefully.

I'm using a Python module for grabbing shared application settings, which I'm deploying in a Rez package. For a few settings (like resolution presets), the only option for some apps (Clarisse, for example) is to have a config text file ready when the app launches.

I'd like it to be dynamic -- so having it generated at rez-env time would be a good time to do it. But I can also do it through a launcher script, which will be run in the resolved environment, so there are other ways to do what I'm after.

**Comment by nerdvegas** [comment]
Ok got you. Yeah this comes up sometimes.

So what you're really talking about is a new function in package.py that
just gets executed in the resolved environment - basically a fragment of a
launcher script (for eg) within the package definition itself. That would
not be a function in the way that "commands" is, because it wouldn't use
the rex api (it only makes sense to use that to construct the target
environment).

I'm not sure if that belongs in the package definition or not. Consider
that you could already do that another way... use "command" (
https://github.com/nerdvegas/rez/wiki/Package-Commands#command) to run some
tool that your package provides, for eg. If we could inject arbitrary
script into the package definition, I would be concerned about that
definition getting large and eating up cache space too.

Does that make sense?
A
