### ISSUE TITLE
Unversioned variants lead to resolution inconsistency

### ISSUE THREAD

**Issue by assumptionsoup** [nerdvegas/rez#697]
I've set up a dummy PySide variant for Maya so that other packages can correctly list PySide as a requirement.  The dummy package is empty so that we defer to Maya's built-in version of PySide.  Today, I started noticing some strange behavior. For reference, I'm using rez version `2.38.1` with minimal changes on windows.

These are my PySide variants:
```
variants = [['platform-windows', 'default'],
            ['platform-windows', 'maya'],
            ['platform-windows', 'mobu'],
            ['platform-osx', 'default'],
            ['platform-linux', 'default']
            ]
```

Let's say the `foo` package requires maya and pyside:
```
requires = [
    'maya-2019',
    'PySide2-5.11.2',
]
```

Now here's where things get strange:
```
> rez env foo
...
PySide2-5.11.2         rez_packages/dev/PySide2/5.11.2/platform-windows/mobu
```
```
> rez env foo maya
...
PySide2-5.11.2         rez_packages/dev/PySide2/5.11.2/platform-windows/maya
```
```
> rez env foo maya-2019
...
PySide2-5.11.2         rez_packages/dev/PySide2/5.11.2/platform-windows/maya
```
I need to request the maya package (any version) to get the maya variant. Otherwise the variant is nondeterministic.  This inconsistency feels like a bug, but perhaps I'm missing something about how variants work. 

Changing foo's requirements to request `maya` rather than `maya-2019` (to exactly match PySide) has no effect.  Changing PySide's variants to have a maya-2019 variant makes `foo` find the right variant again.

**Comment by nerdvegas** [comment]
So to clarify - _non-deterministic_ would mean that you get differing
results when running the same rez-env. Is that the case?

In any case - if you just 'rez-env foo', then you have to get some variant
of pyside (I'm assuming foo requires pyside right!). From what I can see in
your example, there's no reason for rez to pick one variant over another...
eg, this 'default' package isn't anything special, so how should rez decide
to choose it instead of say, maya, or mobu? In this scenario, the variant
selection will seem arbitrary - and it is - but it should be
_deterministic_ - ie you should keep getting the same resolve back when
requesting the same list of packages.

The reason you get the maya variant when maya is present in the request is
by design - see
https://github.com/nerdvegas/rez/wiki/Variants#variant-selection

Hth
A

**Comment by nerdvegas** [comment]
Please let me know if further clarification is needed, otherwise this issue will be closed.

**Comment by assumptionsoup** [comment]
> So to clarify - _non-deterministic_ would mean that you get differing
results when running the same rez-env. Is that the case?

That was my assumption. I thought that resolving the mobu variant was non-derterministic (random). Reading through the docs you linked to, I think my assumption was incorrect, and rez is using a repeatable resolution.  Regardless, this behavior was unexpected to me.

> In any case - if you just 'rez-env foo', then you have to get some variant
of pyside (I'm assuming foo requires pyside right!)

Yes, foo required `maya-2019` and `pyside2-5.11.2` in this example.

> From what I can see in
your example, there's no reason for rez to pick one variant over another...
eg, this 'default' package isn't anything special, so how should rez decide
to choose it instead of say, maya, or mobu?

The default package isn't anything special (it's literally an empty package), but foo requires maya.  Shouldn't that be enough to pick the maya variant over mobu?  Why should explicitly requesting `rez env foo maya` result in a different environment than `rez env foo`, given that foo requires maya?

**Comment by nerdvegas** [comment]
Package requirements aren't taken into account when selecting variants. Due
to how the solver works, a variant could be selected before foo's
requirements are even known to the solver.

Furthermore, what if you did "rez-env foo bah", where both require pyside,
but foo requires maya, and bah requires mobu?

A
