### ISSUE TITLE
Alias persists outside of rez environment

### ISSUE THREAD

**Issue by JanRiebeAxis** [nerdvegas/rez#709]
We noticed that an alias persists after leaving a rez environment.

Example:
Let's assume we have set up up a package 'alias_test' in which we define alias('alias_command', 'echo alias successfully excecuted')
In cmd:
C:\Users\me>rez-env alias_test
> C:\Users\me>alias_command
> C:\Users\me>alias successfully executed
> C:\Users\me>exit
C:\Users\me>alias_command
C:\Users\me>alias successfully excecuted

**Comment by instinct-vfx** [comment]
Good catch. This is because it is created with doskey and a doskey macros are applied to parent shells it seems (just tested). This should not be the case with powershell. Doskey poses quite some challenges and we may have to rethink cmd generally i guess.

**Comment by bfloch** [comment]
@instinct-vfx is right - it is doskey behavior.

There are no exit traps in batch - so it might get ugly to make this work properly - if possible at all.

This might not always be possible but I would also recommend using PowerShell instead for various reasons. cmd should be avoided since it is in maintenance mode and does suffer from severe limitations. That does not mean that you can not launch things that rely on batch files within the environment. You can (and will suffer the consequences 😜 ) - but PowerShell seems more suited to be the main driving shell (for rez) on Windows.

**Comment by JanRiebeAxis** [comment]
Thank you for the quick reply. I will look a bit more into using the powershell instead of cmd.

**Comment by bfloch** [comment]
@nerdvegas I think we can close this as "wontfix" for now.
At most we could add documentation in the alias wiki section.

**Comment by nerdvegas** [comment]
Agreed, cheers.
