### ISSUE TITLE
rez-pip creates .pyc files by default

### ISSUE THREAD

**Issue by instinct-vfx** [nerdvegas/rez#816]
This is an issue if the installed package is a "pure" package (no binary components) because the pyc files might not work with other interpreters.

My proposal would be to add `--no-compile` to pip.py and not generate pyc files at all when using rez-pip.

**Comment by JeanChristopheMorinPerso** [comment]
As discussed on slack, we should add an option called `pip_extra_args` (or something like that) configurable in the rezconfig so everybody can add settings that fits their needs.

For example, a studio could add a `--index-url` for example.

It will give us flexibility and will remove us some maintenance (maintaining the cli for pip arguments).

**Comment by nerdvegas** [comment]
Sounds good. I would pair this with an extra args passthrough option to
rez-pip cli also, which would override the configured `pip_extra_args` if
present.

**Comment by nebukadhezer** [comment]
-- target and --user are probably the two interesting ones where imho rez would always win, or is that needed and wanted that pip then reroutes the destination?

**Comment by lambdaclan** [comment]
Hello everyone, I am working on implementing this as discussed above and based on the discussions you had in slack. The most elegant solution would of course be using the PYTHONWRITEBYTECODE environment variable but since it does not seem to be an option right now I have added the extra functionality to rez-pip cli and rezconfig. I will be submitting a PR soon :+1:

**Comment by bpabel** [comment]
This is solved by switching to python 3, correct? Python 3 writes .pyc files to a `__pycache__` folder with the python version number, so that multiple versions of python will each have their own .pyc files.  

This would only be an issue for people using different versions of python 2 (and I can't imagine anyone is using anything other than 2.7).

**Comment by instinct-vfx** [comment]
I assume python3 fixes incompatible pyc files and possibly also the network load issue. However the case we are seeing is having two incompatible 2.7 interpreters (namely the official binary and the embedded one in 3dsmax).

Beyond that the extra-args make sense for other stuff like index-url as mentioned above (getting around with an env var, but would prefer to be more explicit).
