### ISSUE TITLE
change dir in post_commands()

### ISSUE THREAD

**Issue by col-one** [nerdvegas/rez#860]
Hey again! 
I have some trouble to change the current directory at the end of the rezolved:
```
def post_commands():
    source("cd {this.root}")
```
This command fails, any idea why?  `bash: cd /the/root/path No such file or directory`
Obviously the path exists. 

Thanks a lot.

**Comment by nerdvegas** [comment]
'source' expects a file path, what you want is 'command'.

Thx
A

**Comment by col-one** [comment]
k you right but {this.root} ( or {root} ) doesn't work with command("cd {this.root}")
Is it a limitation ? 

Thanks for your time.

**Comment by nerdvegas** [comment]
Yes expansion doesn't happen in command because that might affect more
complex character escape situations. However you can explicitly escape your
string using 'expandvars', or simply construct the string using value of
'this.root'. See the String Expansion section of Package Commands in the
wiki for more details.

Thx
A

**Comment by col-one** [comment]
the expandvars solution is perfect. Thanks a lot !
