### ISSUE TITLE
rez-pip - no case for ../../include/... file

### ISSUE THREAD

**Issue by smaragden** [nerdvegas/rez#861]
I found an issue with rez-pip trying to install greenlet.
This is due to a similar case as here:
https://github.com/nerdvegas/rez/blob/49cae49a9dd4376b9efb6d571713b716d315b32b/src/rez/pip.py#L426-L432

We need to check for packages reporting files as ../../include/... as well.

To replicate:
`rez-pip -i greenlet`

**Comment by smaragden** [comment]
I found another issue with:
```
rez-pip -i Qt.py
RuntimeError: ("Don't know what to do with source file %r, please file a ticket", u'../../LICENSE')
```

It looks like the ../../include files in greenlet comes from the headers kwarg to setup() in setup.py and should probably be handled. They only seem to be used at build time and are not installed by pip. For now I just install them to {root}/include/

the LICENSE in Qt.py comes from the data_files kwarg without a mapping.
It looks like this is bad practice if you read the docs at:
https://docs.python.org/2/distutils/setupscript.html#installing-additional-files

For now i put those files in {root}/

I do get why you raise as it's impossible to know the purpose of these files.

**Comment by j0yu** [comment]
Hey, I written the patch for the original PR for the `../../include/python`: 
- https://github.com/nerdvegas/rez/pull/855, to solve
- https://github.com/nerdvegas/rez/issues/821

I do agree, it seems like the problem is a bit bigger than just `../../include/python`, I ran into this today pip installing [ranger](https://github.com/ranger/ranger):
```bash
rez pip --install ranger-fm
# RuntimeError: ("Don't know what to do with source file %r, please file a ticket", u'../../share/applications/ranger.desktop')
```

I don't think this idea is going to be good but, what do you think of:
1. if `../../***` is detected, and rez does not know how to handle it,
2. Throw a warning 
3. Substitute the leading `../../` with `{root}/`, install and carry on.

Maybe for step 1, there could be a new setting, e.g. `pip_remaps` dictionary, for re-mapping unknown file paths in the [rez config.py](https://github.com/nerdvegas/rez/wiki/Configuring-Rez) so at least users perform their own substitutions/fixes.

But for now, I think it will be nice and easy to at least fix the error message, which is not formatted correctly.

**Comment by nerdvegas** [comment]
Agreed, this shouldn't be an error, and these files should go to some
configured subfolder, and emit a warning message.

Will get on this soon. Been on hols last 2 weeks hence the radio silence.

Cheers,
A
