### ISSUE TITLE
rez-cp does not overwrite variants

### ISSUE THREAD

**Issue by jopollack** [nerdvegas/rez#870]
I want to rez-cp a package that has been modified to expand the variants list, but rez-cp always appends new variants, with the --overwrite flag doing nothing.

For example, say you have a package.py with the following variants:
```
variants = [
    ['foo-2'],
    ['bar-3'],
]
```
I want to modify this list as follows:
```
variants = [
    ['foo-2', 'pkg-1'],
    ['bar-3'],
]
```
I run rez-cp --overwrite to copy the package over an existing one, I end up getting this:
```
variants = [
    ['foo-2'],
    ['foo-2', 'pkg-1'],
    ['bar-3'],
]
```
I would expect an --overwrite flag to actually overwrite, instead of appending.

**Comment by nerdvegas** [comment]
Hey jopollack,

In Rez, variants are defined solely by their requirements list, not by
their order in the variant list. So in this case an overwrite is not
occurring because the same variant is not being installed (due to the new
dependency list). You should find that --overwrite _will_ actually
overwrite a variant in the case where its requirements are not changed.

Is this causing an issue for you or was it just surprising behaviour?
Besides the extra variant being present in your copied package, there
should be no other issue. And just to clarify, there certainly shouldn't be
any of your code relying on variant indices in copied rez packages to
match. For eg, you can rez-cp variants in backwards order, and the variant
order in the rez-cp'd package would then be different.

Hth
Allan

**Comment by jopollack** [comment]
It's causing an issue as its cropped up during part of a workflow related to updating python packages from python-2 to python-3. The issue is, some python packages have different requirements between python-2 and python-3, so while going back and changing python packages to add a python-3 variant, I need to alter the requires and put the python-2 specific requirements into the python-2 variant. There doesn't seem to be any clean way to do this in rez, though, as I can't overwrite variants, only append new ones, and I fully expect leaving behind the old variants to cause broken resolves.

**Comment by nerdvegas** [comment]
Right yeah I understand.

In this case though I'm not sure what could be done. Since there are no
guarantees of retaining variant order in a copied package (which is by
design) then there isn't really a way to know which variant to overwrite
when its requirements change.

To give some clarity on what I mean wrt not retaining variant order -
you're supposed to be able to copy just a single variant (for eg) using
rez-cp, because perhaps that's all you need. At that point, you have a
variant at index 0 that may not have been index 0 in the source package.
And you can't go changing index order after the fact, because that would
then break any references to the variant (ie in rxt's).

Furthermore, I don't think it would make sense to provide a way to
explicitly set the variant index to overwrite (which may solve your
problem). The reason is that I see rez moving towards hashed variants (
https://github.com/nerdvegas/rez/wiki/Variants#hashed-variants). It's a
long convo to go into why this is, but suffice to say, we'll be moving away
from index-based variants and so in the bigger picture it doesn't make
sense to put in any tooling based around indices.

In this case I would suggest updating your workflow to migrate to a new
package version, and do the rez-cp's from scratch. Although not the same
thing, here at Method we sometimes need to alter a 3rd party package
definition but not payload, and in that case we'll go from a version like
`1.2.3` to `1.2.3.m1`. Perhaps you could take a similar approach?

Let me know how you get on,

Thx
A

**Comment by jopollack** [comment]
I change the version number in other circumstances, but that kind of defeats the purpose of adding variants if I have to change the version schema to adopt python-3. I might as well just have entirely separate packages at that point, since I'm trying to preserve existing resolves and baked out package paths and timestamps.

I imagine I'll just have to find a workaround to preserve the data from the existing package.py that I need and then just erase the whole folder prior to running rez-cp with --allow-empty.

**Comment by nerdvegas** [comment]
Ah, an interesting point here:

"""...since I'm trying to preserve existing resolves..."""

The thing is, if you preserved existing resolves _but_ also overwrote a
variant and changed its requirements, then there's no guarantee that
existing resolves are valid anymore.

A

**Comment by jopollack** [comment]
In my own testing I haven't found any issue there, as our baked out resolves do not contain the full variant path, just the path to the package.py. I can change the variants around and the resolves still work, as long as the package.py location doesn't change, such as by changing the version number.

**Comment by nerdvegas** [comment]
Ah I didn't quite mean that - I meant 'valid' in the sense that there are
no version conflicts, and that the correct package variants are now
selected in the resolve. If you change any requirements after the fact,
then that guarantee is no longer met.

Ie, you could add python-3 to an existing python-2 variant, and technically
an rxt will still resolve, but that resolve is now invalid in the sense
that both python-2.x and python-3.x are configured into the resulting env.

Thx
A

**Comment by jopollack** [comment]
At least in my use case, that isn't an issue since no requirements are actually changing, they're just being defined differently. All the same python-2 packages are still in the resolve, some of them have simply moved out of the requirements and into the variant. The python-3 variant also resolves, as it is not requesting any python-2 specific packages in its requirements anymore. That is not the case with the bad original variant being left behind. It is a python-2.7 variant that is missing requirements, and not only doesn't work, but will likely interfere with the new, proper 2.7 variant.

What I need is the ability to wipe out the variants entirely and completely replace them, while keeping the rest of the package.py the same. At the moment that means I have to copy the rest of the data out of the package.py, then completely delete the folder before replacing it.
