### ISSUE TITLE
[Feature] Support {this.version} in the help attribute

### ISSUE THREAD

**Issue by ColinKennedy** [nerdvegas/rez#899]
It'd be really nice to make versioned documentation in Rez.

## Proposed Behavior
Define a Rez package's `help` attribute generically and give the user the option to expand it to static content on-build. At first I thought `early()` would work but it doesn't.

## Example Definition

```python
name = "my_package"

version = "1.0.0"

@early()
def help():
    return [["Home Page", "http://url.com/{this.version.major}.{this.version.minor}"]]
```

And then on rez-build it'd convert `[["http://url.com/{this.version.major}", "http://url.com/{this.version.minor}"]]` to `[["http://url.com/1.0", "http://url.com/1.0"]]`

Or even better, it'd be nice if it could just take the raw string and then `rez-help` could expand it. .e.g.

```python
name = "my_package"

version = "1.0.0"

help = [["Home Page", "http://url.com/{this.version.major}.{this.version.minor}"]]
```

And then somewhere in the rez-help code ...

`rez-help my_package 1`

```python
_, command = package.help[section]
url = command.format(this=package)
open_in_browser(url)
```

That way I don't have to bother with using `@early` to bake the version directly into the URL.

## Current Workaround

The best I could come up with was to grab version data from the `globals()` when `early()` runs. e.g.

```python
@early()
def help():
    from rez.vendor.version import version as version_

    version__ = version_.Version(version)

    return [
        [
            "Home Page",
            "http://url.com/{version__.major}.{version__.minor}".format(
                version__=version__
            )
        ],
    ]
```

I kept the example text concise but this syntax quickly gets very intense. Especially for a simple URL.

Please let me know if this is already achievable with Rez.

**Comment by nerdvegas** [comment]
Try:

@early()
def help():
    return [["homepage", "http://url.com/%s.%s" % (this.major, this.minor)]]

See
https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#early-binding-functions
.

Your example doesn't work because string literals don't get automatically
expanded like that anywhere except in rex functions within commands, eg
FOO.append('blah_{this.version.major}').

I see your point about having this happen automatically in the help string,
but this would be introducing behaviour that differs wrt all other package
attributes, and I think the resulting inconsistency would outweigh the
convenience. If we were to go that route, I think we should make a change
that applies across the board. For example, something I've considered is
introducing Jinja2 and supporting templating, which you'd then be able to
use in any string literal in the package definition.

Hth
Allan

**Comment by ColinKennedy** [comment]
Hey Allan, thanks for your reply. Your example will definitely work better!

**Comment by ColinKennedy** [comment]
Hi, I think I closed this ticket too prematurely. I gave this a test today and rez raises `AttributeError` when I use `this.major`. Is this a bug? At the moment, I can only get this example to work by defining the attributes myself.

e.g.

```python
name = "my_package"

version = "1.0.0"
major = "1"
minor = "0"

@early()
def help():
    return [["homepage", "http://url.com/%s.%s" % (this.major, this.minor)]]
```

@nerdvegas was that what you were suggesting earlier? If so I think we need a better solution.

**Comment by instinct-vfx** [comment]
Not near Rez atm. But i think it needs to be `this.version.major` rather than `this.major`

**Comment by nerdvegas** [comment]
Apologies yes that was an error in my example.

**Comment by ColinKennedy** [comment]
`this.version` is a string so `this.version.major` raises an AttributeError

e.g.

```python

@early()
def help():
    return [["homepage", "http://url.com/%s.%s" % (this.version.major, this.version.minor)]]
```

That's why earlier I was writing code like `version__ = version_.Version(version)`. Is there a more concise to get it in non-string form? Also, I should've mentioned this earlier I'm using Rez 2.60.1

**Comment by nerdvegas** [comment]
Ah right yes. The thing is, at early binding stage, the package doesn't
exist yet, so all you have access to via `this` is the raw data in the
package.py - that's why version is a string and not a Version object. This
isn't explained in the docs, that should be improved.

I would simply do this explicitly:

@early()
def help():
   major, minor = this.version.split('.')[:2]
    return [["homepage", "http://url.com/%s.%s" % (major, minor)]]

Hth
A
